### PR TITLE
Replaced background svg with png

### PR DESCRIPTION
**Pull request by andreivdev**
### What does it do?

Replaces background svg with png, improving rendering performance significantly

### CODE REVIEW

**Review by janndriessen — APPROVED** [review]
LGTM!

**Comment by embiem** [comment]
The new file is 6.7MB big, that's too much.

What was the issue again with using SVG? Usually SVG doesn't impact performance in my experience.

**Comment by janndriessen** [comment]
> The new file is 6.7MB big, that's too much.
> 
> What was the issue again with using SVG? Usually SVG doesn't impact performance in my experience.

oops I didn't see the size 😅 I think in combination with the animated background the SVG showed an impact.

**Comment by andreivdev** [comment]
I compressed the PNG as much as possible, resulting in a 4.5mb file. 

I don't think there's any more lossless compression possible, the only way to further reduce the size is going jpg.

Should we try that or is 4.5mb acceptable?

**Pull request closed without merging**
