### PR TITLE
[Added] Wallet connect and Metamask

### PR DESCRIPTION
**Pull request by helloitsm3**
### What does it do?
Added wallet components to allow users to connect via either Metamask or Wallet Connect

### Any new dependencies? Why were they added?
wagmi-xyz was used 

### Relevant screenshots/gifs
image
image
image

### Does it close any issues?

Closes #...

### CODE REVIEW

**Comment by janndriessen** [comment]
Didn't check the code but as far as I understood the designs it was probably to show one of these modals (like https://github.com/web3modal/web3modal). So just keeping one button to connect and then opening the modal.

**Comment by embiem** [comment]
> Didn't check the code but as far as I understood the designs it was probably to show one of these modals (like https://github.com/web3modal/web3modal). So just keeping one button to connect and then opening the modal.

I agree. The connect wallet button should open a modal, in which the Injected/Metamask & WalletConnect are listed as choices. We could use chakra's modal component to build it: https://chakra-ui.com/docs/overlay/modal

**Comment by helloitsm3** [comment]
> First of all thanks a lot for the contribution @helloitsm3 !! I'll add some comments in a review, please lmk what you think.
> 
> 
> 
> > Didn't check the code but as far as I understood the designs it was probably to show one of these modals (like https://github.com/web3modal/web3modal). So just keeping one button to connect and then opening the modal.
> 
> 
> 
> I agree. The connect wallet button should open a modal, in which the Injected/Metamask & WalletConnect are listed as choices. We could use chakra's modal component to build it: https://chakra-ui.com/docs/overlay/modal

Sounds good. I didn't think of using a modal since we only have to display 2 buttons and having a modal would be an extra step for users to login which I feel is unnecessary. However, having a modal can make the UI look neat too so I'm okay with implementing that. Will make another commit for it

**Comment by helloitsm3** [comment]
React Confetti now looks like this 
image

Should add a condition to enable this when user successfully mints the token

**Comment by embiem** [comment]
Awesome, I'll get this merged and fix the type error that's erroring the deployment afterwards.

**Pull request merged**
